name: FTP Deploy

on:
  push:
    branches:
      - master
      - Miya
      - Fuji

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload changed files to FTP server (master)
      if: github.ref == 'refs/heads/master'
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./extra105/  # アップロードしたいプロジェクト内のディレクトリを指定
        server-dir: ./
        method: sync  # 差分アップロードを有効にする

    - name: Upload changed files to FTP server (Miya)
      if: github.ref == 'refs/heads/Miya'
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER2 }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./extra105/  # アップロードしたいプロジェクト内のディレクトリを指定
        server-dir: ./
        method: sync  # 差分アップロードを有効にする

    - name: Upload changed files to FTP server (Fuji)
      if: github.ref == 'refs/heads/Fuji'
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER3 }}
        password: ${{ secrets.FTP_PASS2 }}
        local-dir: ./extra105/  # アップロードしたいプロジェクト内のディレクトリを指定
        server-dir: ./
        method: sync  # 差分アップロードを有効にする
